#!/usr/bin/env bash
# Changes the home IP configuration for localhost and facebook.com in /etc/hosts

grep -vE 'localhost|facebook\.com' /etc/hosts > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp

sudo cp /tmp/hosts.tmp /etc/hosts
rm -f /tmp/hosts.tmp
